name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_THREAD }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            > Pushed by: ${{ github.actor }}
            Repository: ${{ github.repository }}:(branch) New commit
            
            ${{ github.sha }} | ${{ github.event.commits[0].message }}
            (url commit: https://github.com/${{ github.repository }}/commit/${{github.sha}}
