name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trim SHA to 7 characters
        id: trim-sha
        run: |
          SHORT_SHA="${{ github.sha }}"
          echo "::set-output name=short_sha::${SHORT_SHA:0:7}"
      - name: Escape special characters for MarkdownV2
        id: escape-chars
        run: |
          # Экранируем имя пользователя
          ACTOR=$(echo "${{ github.actor }}" | sed 's/[_*\[\]()~`>#+\-=|{}.!]/\\&/g')
          # Экранируем название репозитория
          REPO=$(echo "${{ github.repository }}" | sed 's/[_*\[\]()~`>#+\-=|{}.!]/\\&/g')
          # Экранируем сообщение коммита
          COMMIT_MSG=$(echo "${{ github.event.commits[0].message }}" | sed 's/[_*\[\]()~`>#+\-=|{}.!]/\\&/g')
          
          echo "::set-output name=escaped_actor::${ACTOR}"
          echo "::set-output name=escaped_repo::${REPO}"
          echo "::set-output name=escaped_commit_msg::${COMMIT_MSG}"
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdownv2
          message: |
            *Pushed by:* `${{ steps.escape-chars.outputs.escaped_actor }}`
            *Repository:* `${{ steps.escape-chars.outputs.escaped_repo }}` branch: New commit
            
            [`${{ steps.trim-sha.outputs.short_sha }}`](https://github.com/${{ github.repository }}/commit/${{github.sha}}) \\| ${{ steps.escape-chars.outputs.escaped_commit_msg }}
