name: Debug GitHub Event
on: [create]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo "=== GITHUB CONTEXT ==="
          echo "$GITHUB_CONTEXT"
          echo ""
          echo "=== EVENT PAYLOAD ==="
          echo "$EVENT_CONTEXT"
