name: Telegram Notifications

on:
  push:
  pull_request:
    types: [opened, closed, reopened]
  release:
    types: [published]
  create:
  delete:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare notification message
        id: prepare_message
        run: |
          # Определяем тип события
          EVENT_TYPE="${{ github.event_name }}"
          MESSAGE=""

          # Обработка PUSH события
          if [ "$EVENT_TYPE" = "push" ]; then
            if [ -z "${{ github.event.head_commit.id }}" ]; then
              BRANCH_REF=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
              MESSAGE="Branch deleted: $BRANCH_REF"
            else
              MESSAGE="+ New push in repository

              # Текст в push commit в телеграм
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Author: ${{ github.actor }}
            Commit: ${{ github.event.head_commit.message }}
            URL: ${{ github.event.head_commit.url }}
            fi

          # Обработка создания ветки
          elif [ "$EVENT_TYPE" = "create" ]; then
            if [ "${{ github.ref_type }}" = "branch" ]; then
              MESSAGE="+ Created new brach: ${{ github.ref_name }}"
            elif [ "${{ github.ref_type }}" = "tag" ]; then
              MESSAGE="+ Created new tag: ${{ github.ref_name }}"
            fi

          # Обработка удаления ветки
          elif [ "$EVENT_TYPE" = "delete" ]; then
            if [ "${{ github.ref_type }}" = "branch" ]; then
              MESSAGE="- Deleted branch: ${{ github.ref_name }}"
            elif [ "${{ github.ref_type }}" = "tag" ]; then
              MESSAGE="- Deleted tag: ${{ github.ref_name }}"
            fi

          # Обработка PULL REQUEST
          elif [ "$EVENT_TYPE" = "pull_request" ]; then
            ACTION="${{ github.event.action }}"
            PR_TITLE="${{ github.event.pull_request.title }}"
            PR_AUTHOR="${{ github.event.pull_request.user.login }}"
            PR_URL="${{ github.event.pull_request.html_url }}"
            
            if [ "$ACTION" = "opened" ]; then
              MESSAGE="+ New Pull Request: $PR_TITLE
                      Author: $PR_AUTHOR
                      URL: $PR_URL"
            elif [ "$ACTION" = "closed" ]; then
              if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
                MESSAGE="+ Pull Request accepted: $PR_TITLE
                         Author: $PR_AUTHOR
                         URL: $PR_URL"
              else
                MESSAGE="- Pull Request closed: $PR_TITLE
                         Author: $PR_AUTHOR
                         URL: $PR_URL"
              fi
            elif [ "$ACTION" = "reopened" ]; then
              MESSAGE="+ Pull Request reopened: $PR_TITLE
                       Author: $PR_AUTHOR
                       URL: $PR_URL"
            fi
            
          # Обработка RELEASE
          elif [ "$EVENT_TYPE" = "release" ]; then
            MESSAGE="+ New release: ${{ github.event.release.name }} \n
                     Version: ${{ github.event.release.tag_name }} \n
                     Description: ${{ github.event.release.body }} \n
                     URL: ${{ github.event.release.html_url }}"

          else
            MESSAGE="Event: $EVENT_TYPE"
          fi

          # Экранируем специальные символы для вывода
          MESSAGE="${MESSAGE//'%'/'%25'}"
          MESSAGE="${MESSAGE//$'\n'/'%0A'}"
          MESSAGE="${MESSAGE//$'\r'/'%0D'}"
          
          # Современный формат вывода
          echo "message=$MESSAGE" >> $GITHUB_OUTPUT

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ${{ steps.prepare_message.outputs.message }}
