name: Telegram Notification on Push

on: [push] # Триггер - событие push в любую ветку

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            + Новый push в репозиторий!
            Репозиторий: ${{ github.repository }}:${{ github.ref }}
            Автор: ${{ github.actor }}
            Коммит: ${{ github.event.head_commit.message }}
            Ссылка: ${{ github.event.head_commit.url }}
