name: Telegram Notifications

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare message
        id: prepare_message
        run: |
          echo "message=Test message from ${{ github.event_name }}" >> $GITHUB_OUTPUT

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ${{ steps.prepare_message.outputs.message }}
