name: Telegram Notifications

on:
  push:
  pull_request:
    types: [opened, closed, reopened]
  release:
    types: [published]
  create:
  delete:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare notification message
        id: prepare_message
        run: |
          # Определяем тип события
          EVENT_TYPE="${{ github.event_name }}"
          MESSAGE=""

          # Обработка PUSH события
          if [ "$EVENT_TYPE" = "push" ]; then
            if [ -z "${{ github.event.head_commit.id }}" ]; then
              BRANCH_REF=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
              MESSAGE="🗑️ Ветка удалена: $BRANCH_REF"
            else
              MESSAGE="📌 Новый push в репозиторий\n📂 Репозиторий: ${{ github.repository }}\n🌿 Ветка: ${{ github.ref_name }}\n👤 Автор: ${{ github.actor }}\n💬 Коммит: ${{ github.event.head_commit.message }}\n🔗 Ссылка: ${{ github.event.head_commit.url }}"
            fi

          # Обработка создания ветки
          elif [ "$EVENT_TYPE" = "create" ]; then
            if [ "${{ github.ref_type }}" = "branch" ]; then
              MESSAGE="🌿 Создана новая ветка: ${{ github.ref_name }}"
            elif [ "${{ github.ref_type }}" = "tag" ]; then
              MESSAGE="🏷️ Создан новый тег: ${{ github.ref_name }}"
            fi

          # Обработка удаления ветки
          elif [ "$EVENT_TYPE" = "delete" ]; then
            if [ "${{ github.ref_type }}" = "branch" ]; then
              MESSAGE="🗑️ Удалена ветка: ${{ github.ref_name }}"
            elif [ "${{ github.ref_type }}" = "tag" ]; then
              MESSAGE="🗑️ Удален тег: ${{ github.ref_name }}"
            fi

          # Обработка PULL REQUEST
          elif [ "$EVENT_TYPE" = "pull_request" ]; then
            ACTION="${{ github.event.action }}"
            PR_TITLE="${{ github.event.pull_request.title }}"
            PR_AUTHOR="${{ github.event.pull_request.user.login }}"
            PR_URL="${{ github.event.pull_request.html_url }}"
            
            if [ "$ACTION" = "opened" ]; then
              MESSAGE="🆕 Новый Pull Request: $PR_TITLE\n👤 Автор: $PR_AUTHOR\n🔗 Ссылка: $PR_URL"
            elif [ "$ACTION" = "closed" ]; then
              if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
                MESSAGE="✅ Pull Request принят: $PR_TITLE\n👤 Автор: $PR_AUTHOR\n🔗 Ссылка: $PR_URL"
              else
                MESSAGE="❌ Pull Request закрыт: $PR_TITLE\n👤 Автор: $PR_AUTHOR\n🔗 Ссылка: $PR_URL"
              fi
            elif [ "$ACTION" = "reopened" ]; then
              MESSAGE="🔄 Pull Request reopened: $PR_TITLE\n👤 Автор: $PR_AUTHOR\n🔗 Ссылка: $PR_URL"
            fi

          # Обработка RELEASE
          elif [ "$EVENT_TYPE" = "release" ]; then
            MESSAGE="🎉 Новый релиз: ${{ github.event.release.name }}\n🏷️ Версия: ${{ github.event.release.tag_name }}\n📝 Описание: ${{ github.event.release.body }}\n🔗 Ссылка: ${{ github.event.release.html_url }}"

          else
            MESSAGE="ℹ️ Событие: $EVENT_TYPE"
          fi

          # Экранируем специальные символы для вывода
          MESSAGE="${MESSAGE//'%'/'%25'}"
          MESSAGE="${MESSAGE//$'\n'/'%0A'}"
          MESSAGE="${MESSAGE//$'\r'/'%0D'}"
          
          echo "::set-output name=message::$MESSAGE"

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ${{ steps.prepare_message.outputs.message }}
