name: telegram message
on: [push, release, pull_request, issues, issue_comment, create, delete]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: Notify the commit on Telegram
          uses: EverythingSuckz/github-telegram-notify@main
          with:
            bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
            chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
            topic_id: 6
