name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trim SHA to 7 characters
        id: trimSha
        run: |
          SHORT_SHA="${{ github.sha }}"
          echo "::set-output name=shortSha::${SHORT_SHA:0:7}"

      - name: Extract last part from URL
        id: trimRef
        run: |
          REF=${{ github.ref }}
          SHORT_REF=$(basename "$REF")
          echo "::set-output name=shortRef::$SHORT_REF"
          
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_THREAD }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdownv2
          message: |
            \> Pushed by\: ${{ github.actor }}
            \[${{ github.repository }}\:${{ steps.trimRef.outputs.shortRef }}\] New commit
            
            ${{ steps.trimSha.outputs.shortSha }} \| ${{ format('{0}', github.event.commits[0].message | replace('\n', ' ') | replace('-', '\-') | replace('.', '\.') | replace('(', '\(') | replace(')', '\)') | replace('!', '\!') | replace('_', '\_') | replace('*', '\*') | replace('`', '\`') | replace('[', '\[') | replace(']', '\]') ) }}
            \(https\://github\.com/${{ github.repository }}/commit/${{github.sha}}\)
