name: Telegram Default Notifications
on:
  push:
    branches-ignore: 
      - '**'
    tags-ignore:
      - '**'
  release:
  pull_request:
  issues:
  issue_comment:
  delete:

jobs:
  notify:
    name: Default Notification
    runs-on: ubuntu-latest
    # Добавляем условие, чтобы исключить создание веток/тегов
    if: |
      github.event_name != 'push' || 
      (github.event_name == 'push' && github.event.created == false)
    steps:
      - name: Notify via EverythingSuckz Action
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          chat_id: '${{ secrets.TELEGRAM_CHAT_ID }}'
          topic_id: 6
