name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trim SHA to 7 characters
        id: trimSha
        run: |
          SHORT_SHA="${{ github.sha }}"
          echo "SHORT_SHA=${SHORT_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Extract last part from URL
        id: trimRef
        run: |
          REF=${{ github.ref }}
          SHORT_REF=$(basename "$REF")
          echo "SHORT_REF=$SHORT_REF" >> $GITHUB_OUTPUT
          
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_THREAD }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          message: |
            <b>Pushed by:</b> ${{ github.actor }}
            <b>[${{ github.repository }}:${{ steps.trimRef.outputs.shortRef }}]</b> New commit
            
            <code>${{ steps.trimSha.outputs.shortSha }}</code> | ${{ github.event.commits[0].message }}
            <a href="https://github.com/${{ github.repository }}/commit/${{github.sha}}">View commit</a>
