name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trim SHA to 7 characters
        id: trim-sha
        run: |
          SHORT_SHA="${{ github.sha }}"
          echo "::set-output name=short_sha::${SHORT_SHA:0:7}"

      - name: Extract last part from URL
        id: trim-ref
        run: |
          REF=${{ github.ref }}
          SHORT_REF=$(basename "$REF")
          echo "::set-output name=short_ref::$SHORT_REF"
          
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_THREAD }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdownv2
          message: |
            > Pushed by: ${{ github.actor }}
            [${{ github.repository }}:${{ steps.trim-ref.outputs.short_ref }}] New commit
            
            ${{ steps.trim-sha.outputs.short_sha }} | ${{ github.event.commits[0].message }}
            (https://github.com/${{ github.repository }}/commit/${{github.sha}})
