name: Telegram Create Notifications
on: [create]  # ТОЛЬКО create события

jobs:
  notify:
    name: Custom Create Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Custom create notification
        run: python .github/scripts/telegram_notify.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
