name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trim SHA to 7 characters
        id: trimSha
        run: |
          SHORT_SHA="${{ github.sha }}"
           echo "shortSha=${SHORT_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Extract last part from URL
        id: trimRef
        run: |
          REF=${{ github.ref }}
          SHORT_REF=$(basename "$REF")
          echo "shortRef=$SHORT_REF" >> $GITHUB_OUTPUT
          
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: 6
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            <b>Pushed by:</b> <a href="https://github.com/${{ github.actor }}">${{ github.actor }}</a>
            <a href="https://github.com/${{ github.repository }}"><b>[${{ github.repository }}:${{ steps.trimRef.outputs.shortRef }}]</b> 1 New commit</a>
            
            <blockquote><a href="https://github.com/${{ github.repository }}/commit/${{github.sha}}">${{ steps.trimSha.outputs.shortSha }}</a> | ${{ github.event.commits[0].message }}</blockquote>
