name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trim SHA to 7 characters
        id: trimSha
        run: |
          SHORT_SHA="${{ github.sha }}"
          echo "SHORT_SHA=${SHORT_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Extract last part from URL
        id: trimRef
        run: |
          REF=${{ github.ref }}
          SHORT_REF=$(basename "$REF")
          echo "SHORT_REF=$SHORT_REF" >> $GITHUB_OUTPUT
      
      - name: Escape commit message
        id: escapeMessage
        run: |
          MESSAGE="${{ github.event.commits[0].message }}"
          # Экранирование специальных символов для MarkdownV2
          ESCAPED_MESSAGE=$(echo "$MESSAGE" | sed -e 's/\./\\./g' \
                                                 -e 's/-/\\-/g' \
                                                 -e 's/(/\\(/g' \
                                                 -e 's/)/\\)/g' \
                                                 -e 's/!/\\!/g' \
                                                 -e 's/_/\\_/g' \
                                                 -e 's/\*/\\*/g' \
                                                 -e 's/`/\\`/g' \
                                                 -e 's/\[/\\[/g' \
                                                 -e 's/\]/\\]/g' \
                                                 -e 's/#/\\#/g' \
                                                 -e 's/+/\\+/g' \
                                                 -e 's/=/\\=/g' \
                                                 -e 's/|/\\|/g' \
                                                 -e 's/{/\\{/g' \
                                                 -e 's/}/\\}/g' \
                                                 -e 's/>/\\>/g' \
                                                 -e 's/</\\</g' \
                                                 -e 's/~/\\~/g' \
                                                 -e "s/'/\\'/g")
          echo "ESCAPED_MESSAGE=$ESCAPED_MESSAGE" >> $GITHUB_OUTPUT
          
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_THREAD }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdownv2
          message: |
            \> Pushed by\: ${{ github.actor }}
            \[${{ github.repository }}\:${{ steps.trimRef.outputs.shortRef }}\] New commit
            
            `${{ steps.trimSha.outputs.shortSha }}` \| ${{ steps.escapeMessage.outputs.ESCAPED_MESSAGE }}
            \(https\://github\.com/${{ github.repository }}/commit/${{github.sha}}\)
